### ISSUE TITLE
Typographical error in README

### ISSUE THREAD

**Issue by evandrix** [fotisk07/Image-Classifier#2]
[Viewing the Jyputer Notebook](https://github.com/fotisk07/Image-Classifier#viewing-the-jyputer-notebook)

> In order to better view and work on the jupyter Notebook I encourage you to use nbviewer . You can simply copy and paste the link to this website and you will be able to edit it without any problem. Alternatively you can clone the repository using
> git clone https://github.com/fotisk07/Image-Classifier/
> then in the command Line type, after you have downloaded jupyter notebook type
> jyputer notebook
> locate the notebook and run it.

[jJ]yputer => [jJ]upyter

**Comment by fotisk07** [comment]
Thank you very much, I will get right on it!
